### ISSUE TITLE
Bug Controller Post

### ISSUE THREAD

**Issue by Boolean-1-coder** [Boolean-1-coder/Example-GIT#3]
Ciao Francesco, mi sono accorto di questo errore nel controller dei Post, puoi verificare e risolvere?

**Comment by FranzCalore** [comment]
Ciao Bryan, credo che il bug potrebbe nascere dal fatto che hai utilizzato il termine "post" e che questa cosa possa creare confusione con gli [Httppost].
Tu che ne pensi @Ericchi ?

**Comment by Pedra96** [comment]
Stò avendo un problema quando creo un Post mi dice "Francesco torna a lavorare"
